use super::config::CompileConstants;

#[derive(Debug, Clone)]
pub struct FormValue {
    pub name: String,
    pub code: i32,
}

#[derive(Debug, Clone)]
pub struct FormCodes {
    pub argsref: FormValue,
    pub args: FormValue,
    pub list: FormValue,
    pub void: FormValue,
    pub int: FormValue,
    pub intlist: FormValue,
    pub intlistref: FormValue,
    pub intref: FormValue,
    pub label: FormValue,
    pub call: FormValue,
    pub scene: FormValue,
    pub global: FormValue,
    pub str_: FormValue,
    pub strlist: FormValue,
    pub strlistref: FormValue,
    pub strref: FormValue,
}

#[derive(Debug, Clone)]
pub struct LexCodes {
    pub none: i32,
    pub eof: i32,
    pub assign: i32,
    pub plus: i32,
    pub minus: i32,
    pub multiple: i32,
    pub divide: i32,
    pub percent: i32,
    pub plus_assign: i32,
    pub minus_assign: i32,
    pub multiple_assign: i32,
    pub divide_assign: i32,
    pub percent_assign: i32,
    pub equal: i32,
    pub not_equal: i32,
    pub greater: i32,
    pub greater_equal: i32,
    pub less: i32,
    pub less_equal: i32,
    pub logical_and: i32,
    pub logical_or: i32,
    pub dot: i32,
    pub comma: i32,
    pub colon: i32,
    pub open_paren: i32,
    pub close_paren: i32,
    pub open_bracket: i32,
    pub close_bracket: i32,
    pub open_brace: i32,
    pub close_brace: i32,
    pub open_sumi: i32,
    pub close_sumi: i32,
    pub val_int: i32,
    pub val_str: i32,
    pub label: i32,
    pub z_label: i32,
    pub command: i32,
    pub property: i32,
    pub goto: i32,
    pub gosub: i32,
    pub gosubstr: i32,
    pub return_: i32,
    pub if_: i32,
    pub elseif: i32,
    pub else_: i32,
    pub for_: i32,
    pub while_: i32,
    pub continue_: i32,
    pub break_: i32,
    pub switch: i32,
    pub case: i32,
    pub default: i32,
    pub unknown: i32,
    pub tilde: i32,
    pub and: i32,
    pub or: i32,
    pub hat: i32,
    pub sl: i32,
    pub sr: i32,
    pub and_assign: i32,
    pub or_assign: i32,
    pub hat_assign: i32,
    pub sl_assign: i32,
    pub sr_assign: i32,
    pub sr3: i32,
    pub sr3_assign: i32,
}

#[derive(Debug, Clone)]
pub struct OperatorCodes {
    pub none: i32,
    pub plus: i32,
    pub minus: i32,
    pub multiple: i32,
    pub divide: i32,
    pub remainder: i32,
    pub equal: i32,
    pub not_equal: i32,
    pub greater: i32,
    pub greater_equal: i32,
    pub less: i32,
    pub less_equal: i32,
    pub logical_and: i32,
    pub logical_or: i32,
    pub tilde: i32,
    pub and: i32,
    pub or: i32,
    pub hat: i32,
    pub sl: i32,
    pub sr: i32,
    pub sr3: i32,
}

#[derive(Debug, Clone)]
pub struct BytecodeCodes {
    pub nl: i32,
    pub push: i32,
    pub pop: i32,
    pub copy: i32,
    pub property: i32,
    pub copy_elm: i32,
    pub dec_prop: i32,
    pub elm_point: i32,
    pub arg: i32,
    pub goto: i32,
    pub goto_true: i32,
    pub goto_false: i32,
    pub gosub: i32,
    pub gosubstr: i32,
    pub return_: i32,
    pub eof: i32,
    pub assign: i32,
    pub operate_1: i32,
    pub operate_2: i32,
    pub command: i32,
    pub text: i32,
    pub name: i32,
    pub sel_block_start: i32,
    pub sel_block_end: i32,
}

#[derive(Debug, Clone)]
pub struct ElementCodes {
    pub array: i32,
    pub global_cur_call: i32,
    pub global_msg_block: i32,
    pub owner_call_prop: i32,
    pub owner_user_cmd: i32,
    pub owner_user_prop: i32,
}

#[derive(Debug, Clone)]
pub struct ElementTypeCodes {
    pub property: i32,
    pub command: i32,
}

#[derive(Debug, Clone)]
pub struct RuntimeCodes {
    pub forms: FormCodes,
    pub la: LexCodes,
    pub op: OperatorCodes,
    pub cd: BytecodeCodes,
    pub elm: ElementCodes,
    pub element_type: ElementTypeCodes,
    pub z_label_count: usize,
}

impl RuntimeCodes {
    pub fn from_constants(constants: &CompileConstants) -> Result<Self, String> {
        Ok(Self {
            forms: FormCodes {
                argsref: form_value(constants, "FM___ARGSREF")?,
                args: form_value(constants, "FM___ARGS")?,
                list: form_value(constants, "FM_LIST")?,
                void: form_value(constants, "FM_VOID")?,
                int: form_value(constants, "FM_INT")?,
                intlist: form_value(constants, "FM_INTLIST")?,
                intlistref: form_value(constants, "FM_INTLISTREF")?,
                intref: form_value(constants, "FM_INTREF")?,
                label: form_value(constants, "FM_LABEL")?,
                call: form_value(constants, "FM_CALL")?,
                scene: form_value(constants, "FM_SCENE")?,
                global: form_value(constants, "FM_GLOBAL")?,
                str_: form_value(constants, "FM_STR")?,
                strlist: form_value(constants, "FM_STRLIST")?,
                strlistref: form_value(constants, "FM_STRLISTREF")?,
                strref: form_value(constants, "FM_STRREF")?,
            },
            la: LexCodes {
                none: constants.la("NONE")?,
                eof: constants.la("EOF")?,
                assign: constants.la("ASSIGN")?,
                plus: constants.la("PLUS")?,
                minus: constants.la("MINUS")?,
                multiple: constants.la("MULTIPLE")?,
                divide: constants.la("DIVIDE")?,
                percent: constants.la("PERCENT")?,
                plus_assign: constants.la("PLUS_ASSIGN")?,
                minus_assign: constants.la("MINUS_ASSIGN")?,
                multiple_assign: constants.la("MULTIPLE_ASSIGN")?,
                divide_assign: constants.la("DIVIDE_ASSIGN")?,
                percent_assign: constants.la("PERCENT_ASSIGN")?,
                equal: constants.la("EQUAL")?,
                not_equal: constants.la("NOT_EQUAL")?,
                greater: constants.la("GREATER")?,
                greater_equal: constants.la("GREATER_EQUAL")?,
                less: constants.la("LESS")?,
                less_equal: constants.la("LESS_EQUAL")?,
                logical_and: constants.la("LOGICAL_AND")?,
                logical_or: constants.la("LOGICAL_OR")?,
                dot: constants.la("DOT")?,
                comma: constants.la("COMMA")?,
                colon: constants.la("COLON")?,
                open_paren: constants.la("OPEN_PAREN")?,
                close_paren: constants.la("CLOSE_PAREN")?,
                open_bracket: constants.la("OPEN_BRACKET")?,
                close_bracket: constants.la("CLOSE_BRACKET")?,
                open_brace: constants.la("OPEN_BRACE")?,
                close_brace: constants.la("CLOSE_BRACE")?,
                open_sumi: constants.la("OPEN_SUMI")?,
                close_sumi: constants.la("CLOSE_SUMI")?,
                val_int: constants.la("VAL_INT")?,
                val_str: constants.la("VAL_STR")?,
                label: constants.la("LABEL")?,
                z_label: constants.la("Z_LABEL")?,
                command: constants.la("COMMAND")?,
                property: constants.la("PROPERTY")?,
                goto: constants.la("GOTO")?,
                gosub: constants.la("GOSUB")?,
                gosubstr: constants.la("GOSUBSTR")?,
                return_: constants.la("RETURN")?,
                if_: constants.la("IF")?,
                elseif: constants.la("ELSEIF")?,
                else_: constants.la("ELSE")?,
                for_: constants.la("FOR")?,
                while_: constants.la("WHILE")?,
                continue_: constants.la("CONTINUE")?,
                break_: constants.la("BREAK")?,
                switch: constants.la("SWITCH")?,
                case: constants.la("CASE")?,
                default: constants.la("DEFAULT")?,
                unknown: constants.la("UNKNOWN")?,
                tilde: constants.la("TILDE")?,
                and: constants.la("AND")?,
                or: constants.la("OR")?,
                hat: constants.la("HAT")?,
                sl: constants.la("SL")?,
                sr: constants.la("SR")?,
                and_assign: constants.la("AND_ASSIGN")?,
                or_assign: constants.la("OR_ASSIGN")?,
                hat_assign: constants.la("HAT_ASSIGN")?,
                sl_assign: constants.la("SL_ASSIGN")?,
                sr_assign: constants.la("SR_ASSIGN")?,
                sr3: constants.la("SR3")?,
                sr3_assign: constants.la("SR3_ASSIGN")?,
            },
            op: OperatorCodes {
                none: constants.op("OP_NONE")?,
                plus: constants.op("OP_PLUS")?,
                minus: constants.op("OP_MINUS")?,
                multiple: constants.op("OP_MULTIPLE")?,
                divide: constants.op("OP_DIVIDE")?,
                remainder: constants.op("OP_AMARI")?,
                equal: constants.op("OP_EQUAL")?,
                not_equal: constants.op("OP_NOT_EQUAL")?,
                greater: constants.op("OP_GREATER")?,
                greater_equal: constants.op("OP_GREATER_EQUAL")?,
                less: constants.op("OP_LESS")?,
                less_equal: constants.op("OP_LESS_EQUAL")?,
                logical_and: constants.op("OP_LOGICAL_AND")?,
                logical_or: constants.op("OP_LOGICAL_OR")?,
                tilde: constants.op("OP_TILDE")?,
                and: constants.op("OP_AND")?,
                or: constants.op("OP_OR")?,
                hat: constants.op("OP_HAT")?,
                sl: constants.op("OP_SL")?,
                sr: constants.op("OP_SR")?,
                sr3: constants.op("OP_SR3")?,
            },
            cd: BytecodeCodes {
                nl: constants.cd("CD_NL")?,
                push: constants.cd("CD_PUSH")?,
                pop: constants.cd("CD_POP")?,
                copy: constants.cd("CD_COPY")?,
                property: constants.cd("CD_PROPERTY")?,
                copy_elm: constants.cd("CD_COPY_ELM")?,
                dec_prop: constants.cd("CD_DEC_PROP")?,
                elm_point: constants.cd("CD_ELM_POINT")?,
                arg: constants.cd("CD_ARG")?,
                goto: constants.cd("CD_GOTO")?,
                goto_true: constants.cd("CD_GOTO_TRUE")?,
                goto_false: constants.cd("CD_GOTO_FALSE")?,
                gosub: constants.cd("CD_GOSUB")?,
                gosubstr: constants.cd("CD_GOSUBSTR")?,
                return_: constants.cd("CD_RETURN")?,
                eof: constants.cd("CD_EOF")?,
                assign: constants.cd("CD_ASSIGN")?,
                operate_1: constants.cd("CD_OPERATE_1")?,
                operate_2: constants.cd("CD_OPERATE_2")?,
                command: constants.cd("CD_COMMAND")?,
                text: constants.cd("CD_TEXT")?,
                name: constants.cd("CD_NAME")?,
                sel_block_start: constants.cd("CD_SEL_BLOCK_START")?,
                sel_block_end: constants.cd("CD_SEL_BLOCK_END")?,
            },
            elm: ElementCodes {
                array: constants.element("ELM_ARRAY")?,
                global_cur_call: constants.element("ELM_GLOBAL_CUR_CALL")?,
                global_msg_block: constants.element("ELM_GLOBAL_MSG_BLOCK")?,
                owner_call_prop: constants.element("ELM_OWNER_CALL_PROP")?,
                owner_user_cmd: constants.element("ELM_OWNER_USER_CMD")?,
                owner_user_prop: constants.element("ELM_OWNER_USER_PROP")?,
            },
            element_type: ElementTypeCodes {
                property: constants.element_type("ET_PROPERTY")?,
                command: constants.element_type("ET_COMMAND")?,
            },
            z_label_count: constants.z_label_count,
        })
    }
}

fn form_value(constants: &CompileConstants, name: &str) -> Result<FormValue, String> {
    let form = constants.form_name(name)?.to_string();
    let code = constants.form_code_of(&form)?;
    Ok(FormValue { name: form, code })
}
